routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CanHoController;
use App\Http\Controllers\ThanhVienController;
use App\Http\Controllers\HoaDonController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return redirect('/login');
});

Route::get('/dashboard', function () {
    return redirect('/canho');
});

Route::resource("/canho",CanHoController::class)->middleware('auth');
Route::resource("/thanhvien",ThanhVienController::class)->middleware('auth');


//Route::middleware([
//    'auth:sanctum',
//    config('jetstream.auth_session'),
//    'verified'
//])->group(function () {
//    Route::get('/canho', function () {
//        return view('index');
//    })->name('index');
//});

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

app/View/Components/GuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class GuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.guest');
    }
}

resources/views/Edit.blade.php
@extends("layout")

@section("content")
    <div class="container-xl">
        <div class="table-responsive" style="overflow: hidden">
            <div class="table-wrapper">
                <div class="table-title">
                    <div class="row" style="display: flex; align-items: center">
                        <div class="col-sm-6">
                            <h2>Chỉnh sửa <b>Thành viên: {{ $thanhvien->thanhVien_ma }}</b></h2>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-content">
                <form action="{{route('thanhvien.update', $thanhvien->id)}}" method="POST">
                    <div class="modal-body">
                        <div class="form-group">
                            <strong>Họ và tên chủ sở hữu</strong>
                            <input type="text" name="thanhVien_ten" value="123" class="form-control" placeholder="Nhập họ và tên">
                        </div>
                        <div class="form-group">
                            <strong>Loại</strong>
                            <select name="thanhVien_loai" id="" class="form-select">
                                <option value="1">Chủ sở hữu</option>
                                <option value="2">Thành viên</option>
                            </select>
                        </div>

                    </div>
                    <div class="modal-footer">
                        <a type="button" class="btn btn-default" data-dismiss="modal" href="{{route('canho.index') }}">Huỷ bỏ</a>
                        <input type="submit" class="btn btn-success" value="Chỉnh sửa">
                    </div>
                </form>
            </div>

        </div>

    </div>
@endsection

resources/views/create.blade.php
    @extends("layout")

    @section("content")
        <div class="container-xl">
            <div class="table-responsive" style="overflow: hidden">
                <div class="table-wrapper">
                    <div class="table-title">
                        <div class="row" style="display: flex; align-items: center">
                            <div class="col-sm-6">
                                <h2>Tạo <b>Căn hộ</b></h2>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-content">
                    <form action="{{route('canho.store') }}" method="POST">
                        @csrf
                        <div class="modal-body">
                            <div class="form-group">
                                <label>Mã căn hộ</label>
                                <input type="text" name="canHo_ma" class="form-control" placeholder="Nhập mã căn hộ">
                            </div>
                            <div class="form-group">
                                <label>Chủ sở hữu</label>
                                <select name="thanhVien_ma" id="" class="form-control">
                                    <option value="">Không có chủ sở hữu</option>
                                    @foreach($danhSachThanhVien as $tv)
                                        <option value="{{ $tv->thanhVien_ma }}">{{ $tv->thanhVien_ten }}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="form-group">
                                <label>Gía</label>
                                <input type="number" name="canHo_giaBan" class="form-control" placeholder="Nhập Gía căn hộ">
                            </div>
                        </div>
                        <div class="modal-footer">
                            <a type="button" class="btn btn-default" data-dismiss="modal" href="{{route('canho.index') }}">Huỷ bỏ</a>
                            <input type="submit" class="btn btn-success" value="Thêm">
                        </div>
                    </form>

                </div>

            </div>

        </div>
    @endsection

resources/views/createHoaDon.blade.php
@extends("layout")

@section("content")
    <div class="container-xl">
        <div class="table-responsive" style="overflow: hidden">
            <div class="table-wrapper">
                <div class="table-title">
                    <div class="row" style="display: flex; align-items: center">
                        <div class="col-sm-6">
                            <h2>Thêm <b>Hóa đơn</b></h2>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-content">
                <form action="{{route('hoadon.store') }}" method="POST">
                    @csrf
                    <div class="modal-body">
                        <div class="form-group">
                            <label>Căn hộ cần thêm</label>
                            <input type="text" name="canHo_ma" class="form-control" placeholder="Nhập mã căn hộ">
                        </div>
                        <div class="form-group">
                            <label>Loại</label>
                            <select name="hoaDon_trangThai" id="" class="form-control">
                                <option value="1">Đã thanh toán</option>
                                <option value="2">Thanh toán</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <label>Mã hóa đơn</label>
                            <input type="text" name="thanhVien_ma" class="form-control">
                        </div>
                        <div class="form-group">
                            <label>Số tiền điện</label>
                            <input type="text" name="tienDien" class="form-control" >
                        </div>
                        <div class="form-group">
                            <label>Số tiền nước</label>
                            <input type="text" name="tienNuoc" class="form-control" >
                        </div>
                        <div class="form-group">
                            <label>Số tiền gửi xe</label>
                            <input type="text" name="tienGuixe" class="form-control">
                        </div>
                    </div>
                    <div class="modal-footer">
                        <a type="button" class="btn btn-default" data-dismiss="modal" href="{{route('hoadon.index') }}">Huỷ bỏ</a>
                        <input type="submit" class="btn btn-success" value="Thêm">
                    </div>
                </form>

            </div>

        </div>

    </div>
@endsection

resources/views/dashboard.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg">
                <x-jet-welcome />
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/editCanHo.blade.php
@extends("layout")

@section("content")
    <div class="container-xl">
        <div class="table-responsive" style="overflow: hidden">
            <div class="table-wrapper">
                <div class="table-title">
                    <div class="row" style="display: flex; align-items: center">
                        <div class="col-sm-6">
                            <h2>Chỉnh sửa <b>Căn hộ: {{ $canho->canHo_ma }}</b></h2>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-content">
                <form action="{{route('canho.update', $canho->id)}}" method="POST">
                    <div class="modal-body">
                        <div class="form-group">
                            <label>Chủ sở hữu</label>
                            <select name="thanhVien_ma" id="" class="form-control">
                                <option value="">Không có chủ sở hữu</option>
                                @foreach($danhSachThanhVien as $tv)
                                    <option value="{{ $tv->thanhVien_ma }}">{{ $tv->thanhVien_ten }}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="form-group">
                            <label>Gía</label>
                            <input type="number" name="canHo_giaBan" class="form-control" placeholder="Nhập Gía căn hộ">
                        </div>

                    </div>
                    <div class="modal-footer">
                        <a type="button" class="btn btn-default" data-dismiss="modal" href="{{route('canho.index') }}">Huỷ bỏ</a>
                        <input type="submit" class="btn btn-success" value="Chỉnh sửa">
                    </div>
                </form>
            </div>

        </div>

    </div>
@endsection

resources/views/index.blade.php
@extends('layout')

@section('content')
    <div class="container-xl">
        <div class="table-responsive" style="overflow: hidden">
            <div class="table-wrapper">
                <div class="table-title">
                    <div class="row" style="display: flex; align-items: center">
                        <div class="col-sm-6">
                            <h2>Quản lý <b>Căn hộ </b></h2>
                        </div>
                        <div class="col-sm-6" style="display: flex;justify-content: flex-end; align-items: center;">
                            <a style="display: flex; align-items: center; margin-right: 5px" href="{{route('canho.create') }}" class="btn btn-success" data-toggle="modal">

                                <i class="material-icons">&#xE147;</i>
                                <span style="margin-left: 5px">Thêm căn hộ</span>
                            </a>
                        </div>
                    </div>
                </div>
                <table class="table table-striped table-hover">
                    <thead>
                    <tr>
                        <th>Mã căn hộ</th>
                        <th>Tên chủ sở hữu</th>
                        <th>Tình trạng</th>
                        <th>Giá</th>
                    </tr>
                    </thead>
                    <tbody>
                        @foreach ($canHo as $ch)
                            <tr>
                                <td>
                                    {{ $ch->canHo_ma }}
                                </td>
                                <td>
                                    {{ $ch->chuSoHuu_ten }}
                                </td>
                                <td>
                                    {{ ($ch->canHo_trangThai == '1') ? 'Đã sở hữu' : 'Chưa sở hữu' }}
                                </td>
                                <td>
                                    {{ $ch->canHo_giaBan }}
                                </td>
                                <td>

                                <td>
                                    <a href="{{route('canho.edit',$ch->id) }}" class="edit" data-toggle="modal"><i class="material-icons" data-toggle="tooltip" title="Edit">&#xE254;</i></a>
                                    <button ondblclick="{{route('canho.destroy', $ch->id) }}" class="delete" data-toggle="modal"><i class="material-icons" data-toggle="tooltip" title="Delete">&#xE872;</i></button>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection

resources/views/indexThanhVien.blade.php
@extends('layout')

@section('content')
    <div class="container-xl">
        <div class="table-responsive">
            <div class="table-wrapper">
                <div class="table-title">
                    <div class="row d-flex align-items-center">
                        <div class="col-sm-6">
                            <h2>Quản lý <b>Thành Viên</b></h2>
                        </div>
                            <div class="col-sm-6" style="display: flex;justify-content: flex-end; align-items: center;">
                                <a style="display: flex; align-items: center; margin-right: 5px" href="{{route('thanhvien.create') }}" class="btn btn-success" data-toggle="modal">

                                    <i class="material-icons">&#xE147;</i>
                                    <span style="margin-left: 5px">Thêm thành viên</span>
                                </a>
                            </div>
                    </div>
                </div>
                <table class="table table-striped table-hover">
                    <thead>
                    <tr>

                        <th>Mã Thành Viên</th>
                        <th>Tên Thành Viên</th>
                        <th>Căn Hộ</th>
                        <th>Loại</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach ($thanhvien as $tv)
                        <tr>
                            <td>{{ $tv ->thanhVien_ma }}</td>
                            <td>{{ $tv ->thanhVien_ten }}</td>
                            <td>{{ $tv ->canho }}</td>
                            @if ($tv ->loai == 1)
                            <td>Chủ sở hữu</td>
                            @elseif ($tv ->loai == 2)
                            <td>Thành viên</td>
                            @endif
                            <td>
                                <a href="{{route('thanhvien.edit',$tv->id) }}" class="edit" data-toggle="modal"><i class="material-icons" data-toggle="tooltip" title="Edit">&#xE254;</i></a>
                                <button ondblclick="{{route('thanhvien.destroy', $tv->id) }}" class="delete" data-toggle="modal"><i class="material-icons" data-toggle="tooltip" title="Delete">&#xE872;</i></button>
                            </td>

                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <!-- Delete Modal HTML -->
@endsection

resources/views/layout.blade.php
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="UTF-8">

    <link rel="apple-touch-icon" type="image/png"
          href="https://cpwebassets.codepen.io/assets/favicon/apple-touch-icon-5ae1a0698dcc2402e9712f7d01ed509a57814f994c660df9f7a952f3060705ee.png" />
    <meta name="apple-mobile-web-app-title" content="CodePen">

    <link rel="shortcut icon" type="image/x-icon"
          href="https://cpwebassets.codepen.io/assets/favicon/favicon-aec34940fbc1a6e787974dcd360f2c6b63348d4b1f4e06c77743096d55480f33.ico" />

    <link rel="mask-icon" type="image/x-icon"
          href="https://cpwebassets.codepen.io/assets/favicon/logo-pin-8f3771b1072e3c38bd662872f6b673a722f4b3ca2421637d5596661b4e2132cc.svg"
          color="#111" />


    <title>Quản lý chung cư</title>

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto|Varela+Round">
    <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css'>
    <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css'>
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
{{--    <link href="{{ asset('style.css') }}" rel="stylesheet">--}}


    <style>
        body {
            margin-top: 50px;
            background-color: #fff;
            font-family: Arial, sans-serif;
            font-size: 14px;
            letter-spacing: 0.01em;
            color: #39464e;
        }

        .navbar-default {
            background-color: #FFF;
            margin-left: 200px;
        }

        /*main side bar*/
        .msb {
            width: 200px;
            background-color: #F5F7F9;
            position: fixed;
            left: 0;
            top: 0;
            right: auto;
            min-height: 100%;
            overflow-y: auto;
            white-space: nowrap;
            height: 100%;
            z-index: 1;
            border-right: 1px solid #ddd;
        }

        .msb .navbar {
            border: none;
            margin-left: 0;
            background-color: inherit;
        }

        .msb .navbar-header {
            width: 100%;
            border-bottom: 1px solid #e7e7e7;
            margin-bottom: 20px;
            background: #fff;
        }

        .msb .navbar-nav .panel {
            border: 0 none;
            box-shadow: none;
            margin: 0;
            background: inherit;
        }

        .msb .navbar-nav li {
            display: block;
            width: 100%;
        }

        .msb .navbar-nav li a {
            padding: 15px;
            color: #5f5f5f;
        }

        .msb .navbar-nav li a .glyphicon,
        .msb .navbar-nav li a .fa {
            margin-right: 8px;
        }

        .msb .nb {
            padding-top: 5px;
            padding-left: 10px;
            margin-bottom: 30px;
            overflow: hidden;
        }

        ul.nv,
        ul.ns {
            position: relative;
            padding: 0;
            list-style: none;
        }

        .nv {
            /*ns: nav-sub*/
        }

        .nv li {
            display: block;
            position: relative;
        }

        .nv li::before {
            clear: both;
            content: "";
            display: table;
        }

        .nv li a {
            color: #444;
            padding: 10px 25px;
            display: block;
            vertical-align: middle;
        }

        .nv li a .ic {
            font-size: 16px;
            margin-right: 5px;
            font-weight: 300;
            display: inline-block;
        }

        .nv .ns li a {
            padding: 10px 50px;
        }

        /*main content wrapper*/
        .mcw {
            margin-left: 200px;
            position: relative;
            min-height: 100%;
            /*content view*/
        }

        /*globals*/
        a,
        a:focus,
        a:hover {
            text-decoration: none;
        }

        .inbox .container-fluid {
            padding-left: 0;
            padding-right: 0;
        }

        .inbox ul,
        .inbox li {
            margin: 0;
            padding: 0;
        }

        .inbox ul li {
            list-style: none;
        }

        .inbox ul li a {
            display: block;
            padding: 10px 20px;
        }

        .msb,
        .mnb {
            -moz-animation: slidein 300ms forwards;
            -o-animation: slidein 300ms forwards;
            -webkit-animation: slidein 300ms forwards;
            animation: slidein 300ms forwards;
            -webkit-transform-style: preserve-3d;
            transform-style: preserve-3d;
        }

        .mcw {
            -moz-animation: bodyslidein 300ms forwards;
            -o-animation: bodyslidein 300ms forwards;
            -webkit-animation: bodyslidein 300ms forwards;
            animation: bodyslidein 300ms forwards;
            -webkit-transform-style: preserve-3d;
            transform-style: preserve-3d;
        }

        body.msb-x .mcw,
        body.msb-x .mnb {
            margin-left: 0;
            -moz-animation: bodyslideout 300ms forwards;
            -o-animation: bodyslideout 300ms forwards;
            -webkit-animation: bodyslideout 300ms forwards;
            animation: bodyslideout 300ms forwards;
            -webkit-transform-style: preserve-3d;
            transform-style: preserve-3d;
        }

        body.msb-x .msb {
            -moz-animation: slideout 300ms forwards;
            -o-animation: slideout 300ms forwards;
            -webkit-animation: slideout 300ms forwards;
            animation: slideout 300ms forwards;
            -webkit-transform-style: preserve-3d;
            transform-style: preserve-3d;
        }

        /* Slide in animation */
        @-moz-keyframes slidein {
            0% {
                left: -200px;
            }

            100% {
                left: 0;
            }
        }

        @-webkit-keyframes slidein {
            0% {
                left: -200px;
            }

            100% {
                left: 0;
            }
        }

        @keyframes slidein {
            0% {
                left: -200px;
            }

            100% {
                left: 0;
            }
        }

        @-moz-keyframes slideout {
            0% {
                left: 0;
            }

            100% {
                left: -200px;
            }
        }

        @-webkit-keyframes slideout {
            0% {
                left: 0;
            }

            100% {
                left: -200px;
            }
        }

        @keyframes slideout {
            0% {
                left: 0;
            }

            100% {
                left: -200px;
            }
        }

        @-moz-keyframes bodyslidein {
            0% {
                left: 0;
            }

            100% {
                margin-left: 200px;
            }
        }

        @-webkit-keyframes bodyslidein {
            0% {
                left: 0;
            }

            100% {
                left: 0;
            }
        }

        @keyframes bodyslidein {
            0% {
                margin-left: 0;
            }

            100% {
                margin-left: 200px;
            }
        }

        @-moz-keyframes bodyslideout {
            0% {
                margin-left: 200px;
            }

            100% {
                margin-right: 0;
            }
        }

        @-webkit-keyframes bodyslideout {
            0% {
                margin-left: 200px;
            }

            100% {
                margin-left: 0;
            }
        }

        @keyframes bodyslideout {
            0% {
                margin-left: 200px;
            }

            100% {
                margin-left: 0;
            }
        }
    </style>

    <script>
        window.console = window.console || function (t) {};
    </script>



    <script>
        if (document.location.search.match(/type=embed/gi)) {
            window.parent.postMessage("resize", "*");
        }
    </script>


</head>

<body translate="no">
<nav class="mnb navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <i class="ic fa fa-bars"></i>
            </button>
            <div style="padding: 15px 0;">
                <a href="#" id="msbo"><i class="ic fa fa-bars"></i></a>
            </div>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                       aria-expanded="false">User<span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li style="display: flex; justify-content: center">
                            <form method="POST" action="{{ route('logout') }}" class="inline">
                                @csrf

                                <button type="submit" class="btn btn-success">
                                    Đăng xuất
                                </button>
                            </form>
                        </li>
                    </ul>
                </li>

            </ul>

        </div>
    </div>
</nav>
<!--msb: main sidebar-->
<div class="msb" id="msb">
    <nav class="navbar navbar-default" role="navigation">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <div class="brand-wrapper">
                <!-- Brand -->
                <div class="brand-name-wrapper">
                    <a class="navbar-brand" href="#">
                        Quản lý chung cư
                    </a>
                </div>

            </div>

        </div>

        <!-- Main Menu -->
        <div class="side-menu-container">
            <ul class="nav navbar-nav">

                <li class="{{ Route::is('canho.*') || Route::is('canho.*')  ? 'active' : '' }}">
                    <a href="{{route('canho.index') }}"><i class="fa fa-dashboard"></i> Căn hộ</a>
                </li>
                <li class="{{ Route::is('thanhvien.*') || Route::is('thanhvien.*')  ? 'active' : '' }}">
                    <a href="{{route('thanhvien.index') }}"><i class="fa fa-puzzle-piece"></i> Thành Viên</a>
                </li>
                <li>
                    <a href="#"><i class="fa fa-heart"></i> Hoá đơn</a>
                </li>

                <!-- Dropdown-->
            </ul>
        </div><!-- /.navbar-collapse -->
    </nav>
</div>
<!--main content wrapper-->
<div class="mcw" style="height: calc(100vh - 50px); padding: 30px">
    <!--navigation here-->
    <!--main content view-->
    @yield("content")
</div>
<script
    src="https://cpwebassets.codepen.io/assets/common/stopExecutionOnTimeout-2c7831bb44f98c1391d6a4ffda0e1fd302503391ca806e7fcc7b9b87197aec26.js"></script>

<script src='https://code.jquery.com/jquery-3.1.1.min.js'></script>
<script src='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js'></script>
{{--<script src="{{ asset('script.js') }}"></script>--}}
<script id="rendered-js">
    (function () {
        $('#msbo').on('click', function () {
            $('body').toggleClass('msb-x');
        });
    })();
    //# sourceURL=pen.js
</script>



</body>

</html>

resources/views/policy.blade.php
<x-guest-layout>
    <div class="pt-4 bg-gray-100">
        <div class="min-h-screen flex flex-col items-center pt-6 sm:pt-0">
            <div>
                <x-jet-authentication-card-logo />
            </div>

            <div class="w-full sm:max-w-2xl mt-6 p-6 bg-white shadow-md overflow-hidden sm:rounded-lg prose">
                {!! $policy !!}
            </div>
        </div>
    </div>
</x-guest-layout>

resources/views/terms.blade.php
<x-guest-layout>
    <div class="pt-4 bg-gray-100">
        <div class="min-h-screen flex flex-col items-center pt-6 sm:pt-0">
            <div>
                <x-jet-authentication-card-logo />
            </div>

            <div class="w-full sm:max-w-2xl mt-6 p-6 bg-white shadow-md overflow-hidden sm:rounded-lg prose">
                {!! $terms !!}
            </div>
        </div>
    </div>
</x-guest-layout>

resources/views/thanhVienCreate.blade.php
@extends("layout")

@section("content")
    <div class="container-xl">
        <div class="table-responsive" style="overflow: hidden">
            <div class="table-wrapper">
                <div class="table-title">
                    <div class="row" style="display: flex; align-items: center">
                        <div class="col-sm-6">
                            <h2>Thêm <b>Thành viên</b></h2>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-content">
                <form action="{{route('thanhvien.store') }}" method="POST">
                    @csrf
                    <div class="modal-body">
                        <div class="form-group">
                            <label>Tên</label>
                            <input type="text" name="thanhVien_ten" class="form-control" placeholder="Nhập Gía căn hộ">
                        </div>
                        <div class="form-group">
                            <label>Loại</label>
                            <select name="thanhVien_loai" id="" class="form-control">
                                <option value="1">Chủ sở hữu</option>
                                <option value="2">Thành viên</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <label>Mã thành viên</label>
                            <input type="text" name="thanhVien_ma" class="form-control" placeholder="Nhập mã thành viên">
                        </div>
                        <div class="form-group">
                            <label>Căn hộ</label>
                            <select name="canHo_ma" id="" class="form-control">
                                <option value="">Chọn căn hộ</option>
                                @foreach($danhSachCanHo as $ch)
                                    <option value="{{ $ch->canHo_ma }}">{{ $ch->canHo_ma }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <a type="button" class="btn btn-default" data-dismiss="modal" href="{{route('canho.index') }}">Huỷ bỏ</a>
                        <input type="submit" class="btn btn-success" value="Thêm">
                    </div>
                </form>

            </div>

        </div>

    </div>
@endsection